# 量化交易系统配置文件

# 数据配置
data:
  exchange: "binance"
  symbols: []  # 动态获取新币列表
  timeframe: "15m"
  lookback_days: 14
  min_liquidity: 50000  # 最小流动性要求 (USDT)
  max_spread_bps: 30    # 最大买卖价差 (基点)
  
  # 币安API配置
  api_key: "D3u6kHD7KFfdZDZHGDuvrjvIhH6hiyDr29zCngrfY3hYCOVI3eEQXnwBCpcnXLPb"
  secret_key: "DBBmUQlnXTfp42iLXgQvo10f0vjw83C9u50Rv6Cc5PRdcJ9L8mXKHMjug6lUc2z1"
  sandbox: false  # 使用实盘API

# 策略参数
strategy:
  initial_capital: 2000  # 初始资金 (USDT)
  spot_ratio: 0.5        # 现货比例
  leverage: 4            # 杠杆倍数
  twap_intervals: 3      # TWAP建仓次数
  twap_delay: 30         # TWAP间隔 (秒)
  
  # 趋势判断参数
  trend_ema_short: 20
  trend_ema_long: 50
  volume_threshold: 1.3  # 成交量放大倍数
  funding_rate_threshold: 0.0001  # 资金费率阈值
  
  # 调仓触发点
  reduce_short_levels: [0.20, 0.35, 0.50]  # 相对建仓价涨幅
  reduce_short_ratios: [0.30, 0.30, 0.40]  # 对应平仓比例
  strong_trend_threshold: 0.60  # 强势趋势阈值 (单日涨幅)
  adx_threshold: 25      # ADX阈值
  
  # 趋势转换判断
  trend_reversal_adx: 20
  callback_threshold: 0.30  # 回调阈值

# 风控参数
risk_control:
  max_exposure_ratio: 0.30    # 最大敞口比例
  max_loss_ratio: 0.15        # 最大亏损比例
  time_stop_hours: 12         # 时间止损 (小时)
  price_stop_ratio: 0.10      # 价格止损比例
  margin_usage_limit: 0.70    # 保证金使用率限制
  
  # 成本控制
  fee_rate: 0.001             # 手续费率
  slippage_bps: 35            # 滑点 (基点)

# 回测配置
backtest:
  start_date: null  # 自动获取新币上线时间
  end_date: null
  parallel_workers: 4
  vectorized: true
  
# 输出配置
output:
  save_trades: true
  save_metrics: true
  generate_plots: true
  report_format: "html"

